basePath: /api/v1
host: localhost:7777
info:
  contact: {}
  description: This is a Identity and Access Management API server.
  title: Swagger Identity and Access Management API
  version: "1.0"
paths: {}
swagger: "2.0"
